module.exports = {
    Guilds: "GUILDS",
    GuildMembers: "GUILD_MEMBERS",
    GuildModeration: "GUILD_MODERATION",
    GuildEmojisAndStickers: "GUILD_EMOJIS_AND_STICKERS",
    GuildIntegrations: "GUILD_INTEGRATIONS",
    GuildWebhooks: "GUILD_WEBHOOKS",
    GuildInvites: "GUILD_INVITES",
    GuildVoiceStates: "GUILD_VOICE_STATES",
    GuildPresences: "GUILD_PRESENCES",
    GuildMessages: "GUILD_MESSAGES",
    GuildMessageReactions: "GUILD_MESSAGE_REACTIONS",
    GuildMessageTyping: "GUILD_MESSAGE_TYPING",
    DirectMessages: "DIRECT_MESSAGES",
    DirectMessageReactions: "DIRECT_MESSAGE_REACTIONS",
    DirectMessageTyping: "DIRECT_MESSAGE_TYPING",
    MessageContent: "MESSAGE_CONTENT",
    GuildScheduledEvents: "GUILD_SCHEDULED_EVENTS",
    AutoModerationConfiguration: "AUTO_MODERATION_CONFIGURATION",
    AutoModerationExecution: "AUTO_MODERATION_EXECUTION"
}

module.exports.proper = {
    GUILDS: (1 << 0),
    GUILD_MEMBERS: (1 << 1),
    GUILD_MODERATION: (1 << 2),
    GUILD_EMOJIS_AND_STICKERS: (1 << 3),
    GUILD_INTEGRATIONS: (1 << 4),
    GUILD_WEBHOOKS: (1 << 5),
    GUILD_INVITES: (1 << 6),
    GUILD_VOICE_STATES: (1 << 7),
    GUILD_PRESENCES: (1 << 8),
    GUILD_MESSAGES: (1 << 9),
    GUILD_MESSAGE_REACTIONS: (1 << 10),
    GUILD_MESSAGE_TYPING: (1 << 11),
    DIRECT_MESSAGES: (1 << 12),
    DIRECT_MESSAGE_REACTIONS: (1 << 13),
    DIRECT_MESSAGE_TYPING: (1 << 14),
    MESSAGE_CONTENT: (1 << 15),
    GUILD_SCHEDULED_EVENTS: (1 << 16),
    AUTO_MODERATION_CONFIGURATION: (1 << 20),
    AUTO_MODERATION_EXECUTION: (1 << 21)
}